MODULE_NAME = "moore_fsm"
CLOCK_SIG_NAME = "clk"
RESET_SIG_NAME = "reset"

IN_NET_SIG_NAME = "in"
OUT_REG_SIG_NAME = "out"

INTERMEDIATE_CURRENT_STATE_REG_NAME = "state"
INTERMEDIATE_NEXT_STATE_REG_NAME = "next_state"
